title: Ideation and Prototyping
description: Diana's blog
show_downloads: false

baseurl: "/ideation-and-prototyping" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://dtosca.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# social
author: Diana Tosca
image: /thumbnail-jumbo.png
twitter:
  username: toscadiana

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['posts','about']
